In [6]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [8]:
df.head(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [9]:
df.shape

(569, 33)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    str
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), str(1)
memory usage: 146.8 KB

In [13]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [14]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [15]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [16]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
X_train

array([[-0.59159302,  2.08414861, -0.61302715, ..., -0.65363802,
        -0.73530858, -0.11657588],
       [-0.90683348, -0.84779602, -0.87221166, ..., -0.52403583,
        -0.52022107,  1.28268634],
       [-1.42416559, -0.0851649 , -1.29359024, ...,  0.00718068,
         0.3690213 ,  1.14845167],
       ...,
       [-0.92372136,  1.14946047, -0.93415512, ..., -1.24096466,
         0.24703137, -0.42155705],
       [ 2.96330611,  0.54261071,  3.00292271, ...,  2.0350738 ,
         0.40433417,  0.67648256],
       [-0.83365266, -1.20818572, -0.83838727, ..., -1.14063732,
        -0.52824673, -0.74801578]], shape=(455, 30))

In [18]:
y_train

452    B
474    B
318    B
149    B
327    B
      ..
75     M
487    M
549    B
521    M
354    B
Name: diagnosis, Length: 455, dtype: str

## Label Encoding

In [19]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [20]:
y_train

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0])

### Numpy arrays to PyTorch tensors

In [21]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [22]:
X_train_tensor.shape

torch.Size([455, 30])

In [23]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [24]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

### Important Parameter

In [31]:
learning_rate = 0.1
epochs = 1000

## Training Pipeline

In [32]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.9975539461999383
Epoch: 2, Loss: 3.899633681207195
Epoch: 3, Loss: 3.793632449965787
Epoch: 4, Loss: 3.6817239022020467
Epoch: 5, Loss: 3.5639190151873565
Epoch: 6, Loss: 3.4382585282315463
Epoch: 7, Loss: 3.313734639453293
Epoch: 8, Loss: 3.1884422604875415
Epoch: 9, Loss: 3.058530070606338
Epoch: 10, Loss: 2.927531008879544
Epoch: 11, Loss: 2.7896118936053833
Epoch: 12, Loss: 2.647614720392913
Epoch: 13, Loss: 2.4988961666698883
Epoch: 14, Loss: 2.349572572308229
Epoch: 15, Loss: 2.1947437381706214
Epoch: 16, Loss: 2.0436877535862368
Epoch: 17, Loss: 1.8910242036327212
Epoch: 18, Loss: 1.7452813368273692
Epoch: 19, Loss: 1.6037521373822483
Epoch: 20, Loss: 1.4701875048658752
Epoch: 21, Loss: 1.34514017087758
Epoch: 22, Loss: 1.2338569852983237
Epoch: 23, Loss: 1.1375409499155187
Epoch: 24, Loss: 1.056791953282178
Epoch: 25, Loss: 0.9913089876482815
Epoch: 26, Loss: 0.9397795935559369
Epoch: 27, Loss: 0.9000472441490838
Epoch: 28, Loss: 0.8695542750087945
Epoch: 29, Loss: 0.8458832047975275
Epoch: 30, Loss: 0.827098690426076
Epoch: 31, Loss: 0.8118014695828488
Epoch: 32, Loss: 0.7990289644567842
Epoch: 33, Loss: 0.7881300198321161
Epoch: 34, Loss: 0.778662878193898
Epoch: 35, Loss: 0.7703230996130537
Epoch: 36, Loss: 0.7628956549810096
Epoch: 37, Loss: 0.7562240296458054
Epoch: 38, Loss: 0.7501905962723189
Epoch: 39, Loss: 0.7447042092105575
Epoch: 40, Loss: 0.7396923291532566
Epoch: 41, Loss: 0.7350959510996111
Epoch: 42, Loss: 0.7308662559128489
Epoch: 43, Loss: 0.7269623241953594
Epoch: 44, Loss: 0.7233495136477448
Epoch: 45, Loss: 0.7199982614470367
Epoch: 46, Loss: 0.7168831690299808
Epoch: 47, Loss: 0.7139822829738949
Epoch: 48, Loss: 0.7112765183880275
Epoch: 49, Loss: 0.7087491902048738
Epoch: 50, Loss: 0.7063856288766129
Epoch: 51, Loss: 0.7041728636580835
Epoch: 52, Loss: 0.7020993608377766
Epoch: 53, Loss: 0.7001548070447585
Epoch: 54, Loss: 0.6983299297066325
Epoch: 55, Loss: 0.6966163481856632
Epoch: 56, Loss: 0.6950064502541415
Epoch: 57, Loss: 0.6934932894847202
Epoch: 58, Loss: 0.6920704998840178
Epoch: 59, Loss: 0.6907322247237293
Epoch: 60, Loss: 0.6894730570465462
Epoch: 61, Loss: 0.6882879897617706
Epoch: 62, Loss: 0.6871723736111494
Epoch: 63, Loss: 0.6861218815903541
Epoch: 64, Loss: 0.6851324786650551
Epoch: 65, Loss: 0.6842003958307245
Epoch: 66, Loss: 0.6833221077390605
Epoch: 67, Loss: 0.6824943132571292
Epoch: 68, Loss: 0.681713918443038
Epoch: 69, Loss: 0.680978021518472
Epoch: 70, Loss: 0.6802838994973514
Epoch: 71, Loss: 0.6796289961942936
Epoch: 72, Loss: 0.6790109113890106
Epoch: 73, Loss: 0.6784273909654046
Epoch: 74, Loss: 0.6778763178787011
Epoch: 75, Loss: 0.677355703831939
Epoch: 76, Loss: 0.676863681565754
Epoch: 77, Loss: 0.6763984976836104
Epoch: 78, Loss: 0.6759585059492991
Epoch: 79, Loss: 0.6755421610052728
Epoch: 80, Loss: 0.6751480124698023
Epoch: 81, Loss: 0.6747746993784294
Epoch: 82, Loss: 0.6744209449411661
Epoch: 83, Loss: 0.6740855515915978
Epoch: 84, Loss: 0.6737673963077802
Epoch: 85, Loss: 0.6734654261877461
Epoch: 86, Loss: 0.6731786542647189
Epoch: 87, Loss: 0.672906155548927
Epoch: 88, Loss: 0.6726470632842961
Epoch: 89, Loss: 0.672400565409382
Epoch: 90, Loss: 0.6721659012127424
Epoch: 91, Loss: 0.6719423581736167
Epoch: 92, Loss: 0.6717292689792909
Epoch: 93, Loss: 0.671526008710958
Epoch: 94, Loss: 0.6713319921902233
Epoch: 95, Loss: 0.6711466714787017
Epoch: 96, Loss: 0.6709695335234065
Epoch: 97, Loss: 0.6708000979408786
Epoch: 98, Loss: 0.6706379149332071
Epoch: 99, Loss: 0.670482563329322
Epoch: 100, Loss: 0.670333648745141
Epoch: 101, Loss: 0.6701908018563669
Epoch: 102, Loss: 0.6700536767779419
Epoch: 103, Loss: 0.6699219495443755
Epoch: 104, Loss: 0.6697953166853857
Epoch: 105, Loss: 0.6696734938915042
Epoch: 106, Loss: 0.6695562147645145
Epoch: 107, Loss: 0.6694432296478172
Epoch: 108, Loss: 0.669334304532026
Epoch: 109, Loss: 0.6692292200313199
Epoch: 110, Loss: 0.6691277704262903
Epoch: 111, Loss: 0.6690297627692278
Epoch: 112, Loss: 0.6689350160480039
Epoch: 113, Loss: 0.6688433604049027
Epoch: 114, Loss: 0.6687546364069472
Epoch: 115, Loss: 0.6686686943644649
Epoch: 116, Loss: 0.6685853936948064
Epoch: 117, Loss: 0.6685046023283202
Epoch: 118, Loss: 0.6684261961538421
Epoch: 119, Loss: 0.6683500585011302
Epoch: 120, Loss: 0.6682760796578249
Epoch: 121, Loss: 0.6682041564186597
Epoch: 122, Loss: 0.668134191664793
Epoch: 123, Loss: 0.6680660939712592
Epoch: 124, Loss: 0.6679997772406654
Epoch: 125, Loss: 0.6679351603613799
Epoch: 126, Loss: 0.6678721668885682
Epoch: 127, Loss: 0.6678107247465419
Epoch: 128, Loss: 0.6677507659509823
Epoch: 129, Loss: 0.6676922263496989
Epoch: 130, Loss: 0.6676350453806666
Epoch: 131, Loss: 0.6675791658461729
Epoch: 132, Loss: 0.6675245337019815
Epoch: 133, Loss: 0.6674710978604936
Epoch: 134, Loss: 0.6674188100069557
Epoch: 135, Loss: 0.6673676244278265
Epoch: 136, Loss: 0.6673174978504791
Epoch: 137, Loss: 0.6672683892934633
Epoch: 138, Loss: 0.6672202599266152
Epoch: 139, Loss: 0.6671730729403402
Epoch: 140, Loss: 0.6671267934234519
Epoch: 141, Loss: 0.6670813882489788
Epoch: 142, Loss: 0.6670368259674059
Epoch: 143, Loss: 0.6669930767068422
Epoch: 144, Loss: 0.6669501120796478
Epoch: 145, Loss: 0.666907905095083
Epoch: 146, Loss: 0.6668664300775733
Epoch: 147, Loss: 0.666825662590211
Epoch: 148, Loss: 0.6667855793631422
Epoch: 149, Loss: 0.6667461582265094
Epoch: 150, Loss: 0.666707378047646
Epoch: 151, Loss: 0.6666692186722374
Epoch: 152, Loss: 0.6666316608691808
Epoch: 153, Loss: 0.6665946862789046
Epoch: 154, Loss: 0.6665582773649086
Epoch: 155, Loss: 0.6665224173683173
Epoch: 156, Loss: 0.6664870902652457
Epoch: 157, Loss: 0.6664522807267892
Epoch: 158, Loss: 0.6664179740814701
Epoch: 159, Loss: 0.6663841562799725
Epoch: 160, Loss: 0.6663508138620241
Epoch: 161, Loss: 0.6663179339252762
Epoch: 162, Loss: 0.6662855040960592
Epoch: 163, Loss: 0.6662535125018872
Epoch: 164, Loss: 0.6662219477456007
Epoch: 165, Loss: 0.6661907988810409
Epoch: 166, Loss: 0.6661600553901583
Epoch: 167, Loss: 0.6661297071614631
Epoch: 168, Loss: 0.6660997444697315
Epoch: 169, Loss: 0.6660701579568887
Epoch: 170, Loss: 0.6660409386139933
Epoch: 171, Loss: 0.666012077764256
Epoch: 172, Loss: 0.6659835670470232
Epoch: 173, Loss: 0.6659553984026702
Epoch: 174, Loss: 0.6659275640583424
Epoch: 175, Loss: 0.6659000565144974
Epoch: 176, Loss: 0.6658728685321909
Epoch: 177, Loss: 0.6658459931210702
Epoch: 178, Loss: 0.6658194235280225
Epoch: 179, Loss: 0.6657931532264446
Epoch: 180, Loss: 0.6657671759060929
Epoch: 181, Loss: 0.6657414854634811
Epoch: 182, Loss: 0.665716075992789
Epoch: 183, Loss: 0.6656909417772554
Epoch: 184, Loss: 0.6656660772810252
Epoch: 185, Loss: 0.6656414771414214
Epoch: 186, Loss: 0.6656171361616208
Epoch: 187, Loss: 0.6655930493037071
Epoch: 188, Loss: 0.6655692116820787
Epoch: 189, Loss: 0.6655456185571935
Epoch: 190, Loss: 0.6655222653296289
Epoch: 191, Loss: 0.6654991475344388
Epoch: 192, Loss: 0.6654762608357925
Epoch: 193, Loss: 0.6654536010218762
Epoch: 194, Loss: 0.6654311640000471
Epoch: 195, Loss: 0.6654089457922199
Epoch: 196, Loss: 0.6653869425304775
Epoch: 197, Loss: 0.665365150452892
Epoch: 198, Loss: 0.6653435658995429
Epoch: 199, Loss: 0.665322185308723
Epoch: 200, Loss: 0.6653010052133221
Epoch: 201, Loss: 0.665280022237378
Epoch: 202, Loss: 0.6652592330927852
Epoch: 203, Loss: 0.6652386345761555
Epoch: 204, Loss: 0.6652182235658174
Epoch: 205, Loss: 0.6651979970189539
Epoch: 206, Loss: 0.6651779519688638
Epoch: 207, Loss: 0.6651580855223466
Epoch: 208, Loss: 0.6651383948571996
Epoch: 209, Loss: 0.6651188772198255
Epoch: 210, Loss: 0.6650995299229407
Epoch: 211, Loss: 0.665080350343383
Epoch: 212, Loss: 0.6650613359200109
Epoch: 213, Loss: 0.6650424841516916
Epoch: 214, Loss: 0.665023792595372
Epoch: 215, Loss: 0.6650052588642297
Epoch: 216, Loss: 0.6649868806258983
Epoch: 217, Loss: 0.6649686556007669
Epoch: 218, Loss: 0.6649505815603449
Epoch: 219, Loss: 0.6649326563256944
Epoch: 220, Loss: 0.6649148777659226
Epoch: 221, Loss: 0.6648972437967346
Epoch: 222, Loss: 0.6648797523790414
Epoch: 223, Loss: 0.6648624015176213
Epoch: 224, Loss: 0.6648451892598328
Epoch: 225, Loss: 0.6648281136943767
Epoch: 226, Loss: 0.6648111729501027
Epoch: 227, Loss: 0.6647943651948626
Epoch: 228, Loss: 0.6647776886344037
Epoch: 229, Loss: 0.6647611415113042
Epoch: 230, Loss: 0.6647447221039458
Epoch: 231, Loss: 0.6647284287255246
Epoch: 232, Loss: 0.6647122597230958
Epoch: 233, Loss: 0.6646962134766531
Epoch: 234, Loss: 0.6646802883982393
Epoch: 235, Loss: 0.6646644829310898
Epoch: 236, Loss: 0.6646487955488026
Epoch: 237, Loss: 0.6646332247545396
Epoch: 238, Loss: 0.6646177690802522
Epoch: 239, Loss: 0.6646024270859356
Epoch: 240, Loss: 0.6645871973589057
Epoch: 241, Loss: 0.6645720785131011
Epoch: 242, Loss: 0.6645570691884075
Epoch: 243, Loss: 0.6645421680500042
Epoch: 244, Loss: 0.6645273737877322
Epoch: 245, Loss: 0.6645126851154807
Epoch: 246, Loss: 0.6644981007705953
Epoch: 247, Loss: 0.6644836195133045
Epoch: 248, Loss: 0.6644692401261613
Epoch: 249, Loss: 0.6644549614135061
Epoch: 250, Loss: 0.6644407822009446
Epoch: 251, Loss: 0.6644267013348393
Epoch: 252, Loss: 0.6644127176818202
Epoch: 253, Loss: 0.664398830128308
Epoch: 254, Loss: 0.6643850375800517
Epoch: 255, Loss: 0.6643713389616804
Epoch: 256, Loss: 0.664357733216268
Epoch: 257, Loss: 0.6643442193049107
Epoch: 258, Loss: 0.6643307962063162
Epoch: 259, Loss: 0.6643174629164065
Epoch: 260, Loss: 0.664304218447929
Epoch: 261, Loss: 0.6642910618300819
Epoch: 262, Loss: 0.6642779921081482
Epoch: 263, Loss: 0.6642650083431397
Epoch: 264, Loss: 0.6642521096114524
Epoch: 265, Loss: 0.664239295004531
Epoch: 266, Loss: 0.6642265636285406
Epoch: 267, Loss: 0.6642139146040502
Epoch: 268, Loss: 0.6642013470657235
Epoch: 269, Loss: 0.6641888601620172
Epoch: 270, Loss: 0.6641764530548889
Epoch: 271, Loss: 0.6641641249195125
Epoch: 272, Loss: 0.6641518749439986
Epoch: 273, Loss: 0.6641397023291264
Epoch: 274, Loss: 0.6641276062880797
Epoch: 275, Loss: 0.6641155860461896
Epoch: 276, Loss: 0.6641036408406863
Epoch: 277, Loss: 0.6640917699204545
Epoch: 278, Loss: 0.6640799725457962
Epoch: 279, Loss: 0.6640682479882002
Epoch: 280, Loss: 0.6640565955301156
Epoch: 281, Loss: 0.6640450144647332
Epoch: 282, Loss: 0.6640335040957697
Epoch: 283, Loss: 0.6640220637372604
Epoch: 284, Loss: 0.6640106927133534
Epoch: 285, Loss: 0.6639993903581122
Epoch: 286, Loss: 0.6639881560153208
Epoch: 287, Loss: 0.6639769890382942
Epoch: 288, Loss: 0.6639658887896943
Epoch: 289, Loss: 0.6639548546413488
Epoch: 290, Loss: 0.6639438859740753
Epoch: 291, Loss: 0.6639329821775088
Epoch: 292, Loss: 0.6639221426499348
Epoch: 293, Loss: 0.6639113667981245
Epoch: 294, Loss: 0.6639006540371748
Epoch: 295, Loss: 0.6638900037903526
Epoch: 296, Loss: 0.66387941548894
Epoch: 297, Loss: 0.6638688885720877
Epoch: 298, Loss: 0.6638584224866666
Epoch: 299, Loss: 0.6638480166871268
Epoch: 300, Loss: 0.6638376706353576
Epoch: 301, Loss: 0.663827383800551
Epoch: 302, Loss: 0.6638171556590695
Epoch: 303, Loss: 0.6638069856943152
Epoch: 304, Loss: 0.6637968733966023
Epoch: 305, Loss: 0.6637868182630334
Epoch: 306, Loss: 0.663776819797377
Epoch: 307, Loss: 0.6637668775099491
Epoch: 308, Loss: 0.6637569909174964
Epoch: 309, Loss: 0.663747159543082
Epoch: 310, Loss: 0.663737382915975
Epoch: 311, Loss: 0.6637276605715403
Epoch: 312, Loss: 0.6637179920511329
Epoch: 313, Loss: 0.6637083769019928
Epoch: 314, Loss: 0.6636988146771431
Epoch: 315, Loss: 0.6636893049352898
Epoch: 316, Loss: 0.6636798472407239
Epoch: 317, Loss: 0.6636704411632264
Epoch: 318, Loss: 0.6636610862779729
Epoch: 319, Loss: 0.663651782165443
Epoch: 320, Loss: 0.6636425284113302
Epoch: 321, Loss: 0.6636333246064527
Epoch: 322, Loss: 0.6636241703466692
Epoch: 323, Loss: 0.6636150652327922
Epoch: 324, Loss: 0.6636060088705067
Epoch: 325, Loss: 0.6635970008702887
Epoch: 326, Loss: 0.6635880408473255
Epoch: 327, Loss: 0.6635791284214387
Epoch: 328, Loss: 0.6635702632170069
Epoch: 329, Loss: 0.663561444862892
Epoch: 330, Loss: 0.6635526729923651
Epoch: 331, Loss: 0.663543947243036
Epoch: 332, Loss: 0.6635352672567814
Epoch: 333, Loss: 0.6635266326796772
Epoch: 334, Loss: 0.66351804316193
Epoch: 335, Loss: 0.6635094983578123
Epoch: 336, Loss: 0.6635009979255961
Epoch: 337, Loss: 0.6634925415274898
Epoch: 338, Loss: 0.6634841288295766
Epoch: 339, Loss: 0.6634757595017517
Epoch: 340, Loss: 0.663467433217664
Epoch: 341, Loss: 0.6634591496546567
Epoch: 342, Loss: 0.6634509084937085
Epoch: 343, Loss: 0.6634427094193788
Epoch: 344, Loss: 0.663434552119751
Epoch: 345, Loss: 0.663426436286379
Epoch: 346, Loss: 0.6634183616142325
Epoch: 347, Loss: 0.6634103278016458
Epoch: 348, Loss: 0.6634023345502662
Epoch: 349, Loss: 0.663394381565003
Epoch: 350, Loss: 0.6633864685539782
Epoch: 351, Loss: 0.663378595228479
Epoch: 352, Loss: 0.6633707613029085
Epoch: 353, Loss: 0.6633629664947397
Epoch: 354, Loss: 0.6633552105244706
Epoch: 355, Loss: 0.6633474931155772
Epoch: 356, Loss: 0.6633398139944707
Epoch: 357, Loss: 0.663332172890454
Epoch: 358, Loss: 0.6633245695356786
Epoch: 359, Loss: 0.6633170036651028
Epoch: 360, Loss: 0.6633094750164514
Epoch: 361, Loss: 0.6633019833301746
Epoch: 362, Loss: 0.6632945283494087
Epoch: 363, Loss: 0.6632871098199371
Epoch: 364, Loss: 0.6632797274901525
Epoch: 365, Loss: 0.6632723811110192
Epoch: 366, Loss: 0.6632650704360361
Epoch: 367, Loss: 0.6632577952212012
Epoch: 368, Loss: 0.6632505552249749
Epoch: 369, Loss: 0.6632433502082469
Epoch: 370, Loss: 0.6632361799343002
Epoch: 371, Loss: 0.6632290441687781
Epoch: 372, Loss: 0.6632219426796521
Epoch: 373, Loss: 0.6632148752371876
Epoch: 374, Loss: 0.6632078416139133
Epoch: 375, Loss: 0.6632008415845897
Epoch: 376, Loss: 0.6631938749261779
Epoch: 377, Loss: 0.6631869414178097
Epoch: 378, Loss: 0.6631800408407574
Epoch: 379, Loss: 0.6631731729784055
Epoch: 380, Loss: 0.6631663376162202
Epoch: 381, Loss: 0.6631595345417234
Epoch: 382, Loss: 0.6631527635444632
Epoch: 383, Loss: 0.6631460244159875
Epoch: 384, Loss: 0.6631393169498168
Epoch: 385, Loss: 0.6631326409414182
Epoch: 386, Loss: 0.663125996188179
Epoch: 387, Loss: 0.663119382489382
Epoch: 388, Loss: 0.6631127996461791
Epoch: 389, Loss: 0.6631062474615681
Epoch: 390, Loss: 0.6630997257403678
Epoch: 391, Loss: 0.6630932342891943
Epoch: 392, Loss: 0.6630867729164375
Epoch: 393, Loss: 0.663080341432238
Epoch: 394, Loss: 0.6630739396484648
Epoch: 395, Loss: 0.663067567378693
Epoch: 396, Loss: 0.6630612244381808
Epoch: 397, Loss: 0.6630549106438499
Epoch: 398, Loss: 0.6630486258142629
Epoch: 399, Loss: 0.6630423697696025
Epoch: 400, Loss: 0.6630361423316513
Epoch: 401, Loss: 0.6630299433237722
Epoch: 402, Loss: 0.6630237725708874
Epoch: 403, Loss: 0.6630176298994597
Epoch: 404, Loss: 0.6630115151374727
Epoch: 405, Loss: 0.6630054281144125
Epoch: 406, Loss: 0.6629993686612484
Epoch: 407, Loss: 0.6629933366104154
Epoch: 408, Loss: 0.6629873317957954
Epoch: 409, Loss: 0.6629813540527001
Epoch: 410, Loss: 0.6629754032178528
Epoch: 411, Loss: 0.662969479129372
Epoch: 412, Loss: 0.6629635816267542
Epoch: 413, Loss: 0.6629577105508568
Epoch: 414, Loss: 0.6629518657438828
Epoch: 415, Loss: 0.6629460470493631
Epoch: 416, Loss: 0.6629402543121421
Epoch: 417, Loss: 0.6629344873783617
Epoch: 418, Loss: 0.6629287460954446
Epoch: 419, Loss: 0.6629230303120817
Epoch: 420, Loss: 0.6629173398782142
Epoch: 421, Loss: 0.6629116746450214
Epoch: 422, Loss: 0.6629060344649048
Epoch: 423, Loss: 0.6629004191914747
Epoch: 424, Loss: 0.6628948286795348
Epoch: 425, Loss: 0.6628892627850704
Epoch: 426, Loss: 0.6628837213652332
Epoch: 427, Loss: 0.6628782042783282
Epoch: 428, Loss: 0.6628727113838011
Epoch: 429, Loss: 0.6628672425422246
Epoch: 430, Loss: 0.6628617976152856
Epoch: 431, Loss: 0.6628563764657737
Epoch: 432, Loss: 0.662850978957567
Epoch: 433, Loss: 0.662845604955621
Epoch: 434, Loss: 0.6628402543259563
Epoch: 435, Loss: 0.662834926935647
Epoch: 436, Loss: 0.6628296226528083
Epoch: 437, Loss: 0.6628243413465851
Epoch: 438, Loss: 0.6628190828871411
Epoch: 439, Loss: 0.6628138471456474
Epoch: 440, Loss: 0.6628086339942711
Epoch: 441, Loss: 0.6628034433061646
Epoch: 442, Loss: 0.6627982749554553
Epoch: 443, Loss: 0.662793128817234
Epoch: 444, Loss: 0.6627880047675458
Epoch: 445, Loss: 0.6627829026833785
Epoch: 446, Loss: 0.6627778224426534
Epoch: 447, Loss: 0.662772763924215
Epoch: 448, Loss: 0.6627677270078209
Epoch: 449, Loss: 0.6627627115741327
Epoch: 450, Loss: 0.6627577175047055
Epoch: 451, Loss: 0.6627527446819794
Epoch: 452, Loss: 0.6627477929892698
Epoch: 453, Loss: 0.662742862310758
Epoch: 454, Loss: 0.6627379525314824
Epoch: 455, Loss: 0.6627330635373296
Epoch: 456, Loss: 0.6627281952150259
Epoch: 457, Loss: 0.6627233474521275
Epoch: 458, Loss: 0.6627185201370132
Epoch: 459, Loss: 0.6627137131588752
Epoch: 460, Loss: 0.6627089264077112
Epoch: 461, Loss: 0.6627041597743161
Epoch: 462, Loss: 0.6626994131502731
Epoch: 463, Loss: 0.6626946864279475
Epoch: 464, Loss: 0.6626899795004769
Epoch: 465, Loss: 0.6626852922617644
Epoch: 466, Loss: 0.662680624606471
Epoch: 467, Loss: 0.6626759764300074
Epoch: 468, Loss: 0.6626713476285272
Epoch: 469, Loss: 0.6626667380989193
Epoch: 470, Loss: 0.6626621477388002
Epoch: 471, Loss: 0.6626575764465072
Epoch: 472, Loss: 0.6626530241210922
Epoch: 473, Loss: 0.6626484906623124
Epoch: 474, Loss: 0.662643975970626
Epoch: 475, Loss: 0.6626394799471833
Epoch: 476, Loss: 0.6626350024938216
Epoch: 477, Loss: 0.6626305435130574
Epoch: 478, Loss: 0.6626261029080803
Epoch: 479, Loss: 0.6626216805827472
Epoch: 480, Loss: 0.6626172764415741
Epoch: 481, Loss: 0.6626128903897319
Epoch: 482, Loss: 0.6626085223330389
Epoch: 483, Loss: 0.6626041721779548
Epoch: 484, Loss: 0.6625998398315756
Epoch: 485, Loss: 0.6625955252016256
Epoch: 486, Loss: 0.6625912281964538
Epoch: 487, Loss: 0.662586948725027
Epoch: 488, Loss: 0.6625826866969231
Epoch: 489, Loss: 0.6625784420223275
Epoch: 490, Loss: 0.6625742146120258
Epoch: 491, Loss: 0.6625700043773987
Epoch: 492, Loss: 0.6625658112304169
Epoch: 493, Loss: 0.6625616350836354
Epoch: 494, Loss: 0.6625574758501879
Epoch: 495, Loss: 0.6625533334437821
Epoch: 496, Loss: 0.6625492077786942
Epoch: 497, Loss: 0.6625450987697634
Epoch: 498, Loss: 0.6625410063323878
Epoch: 499, Loss: 0.6625369303825175
Epoch: 500, Loss: 0.6625328708366525
Epoch: 501, Loss: 0.6625288276118347
Epoch: 502, Loss: 0.6625248006256457
Epoch: 503, Loss: 0.6625207897961998
Epoch: 504, Loss: 0.6625167950421411
Epoch: 505, Loss: 0.6625128162826375
Epoch: 506, Loss: 0.662508853437377
Epoch: 507, Loss: 0.6625049064265622
Epoch: 508, Loss: 0.662500975170907
Epoch: 509, Loss: 0.6624970595916313
Epoch: 510, Loss: 0.6624931596104566
Epoch: 511, Loss: 0.6624892751496018
Epoch: 512, Loss: 0.6624854061317791
Epoch: 513, Loss: 0.6624815524801898
Epoch: 514, Loss: 0.6624777141185194
Epoch: 515, Loss: 0.6624738909709342
Epoch: 516, Loss: 0.662470082962077
Epoch: 517, Loss: 0.6624662900170629
Epoch: 518, Loss: 0.6624625120614752
Epoch: 519, Loss: 0.662458749021362
Epoch: 520, Loss: 0.6624550008232316
Epoch: 521, Loss: 0.6624512673940489
Epoch: 522, Loss: 0.6624475486612316
Epoch: 523, Loss: 0.6624438445526465
Epoch: 524, Loss: 0.6624401549966056
Epoch: 525, Loss: 0.6624364799218626
Epoch: 526, Loss: 0.6624328192576089
Epoch: 527, Loss: 0.66242917293347
Epoch: 528, Loss: 0.6624255408795027
Epoch: 529, Loss: 0.6624219230261901
Epoch: 530, Loss: 0.6624183193044402
Epoch: 531, Loss: 0.6624147296455795
Epoch: 532, Loss: 0.6624111539813528
Epoch: 533, Loss: 0.6624075922439175
Epoch: 534, Loss: 0.6624040443658414
Epoch: 535, Loss: 0.6624005102800987
Epoch: 536, Loss: 0.6623969899200676
Epoch: 537, Loss: 0.6623934832195256
Epoch: 538, Loss: 0.6623899901126482
Epoch: 539, Loss: 0.662386510534004
Epoch: 540, Loss: 0.6623830444185526
Epoch: 541, Loss: 0.6623795917016415
Epoch: 542, Loss: 0.6623761523190024
Epoch: 543, Loss: 0.6623727262067481
Epoch: 544, Loss: 0.6623693133013709
Epoch: 545, Loss: 0.6623659135397378

In [33]:
model.bias

tensor([-0.5175], dtype=torch.float64, requires_grad=True)

## Model Evaluation

In [34]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6315789222717285